In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import os
import datetime
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [2]:
df=pd.DataFrame({'id':list(range(5)), 'number':list(range(1,6)) })
df

id  number
0   0       1
1   1       2
2   2       3
3   3       4
4   4       5

In [3]:
df['fizz_buzz'] = df['number']
df

id  number  fizz_buzz
0   0       1          1
1   1       2          2
2   2       3          3
3   3       4          4
4   4       5          5

In [4]:
df.loc[(df.number%3==0) & (df.number%5==0), "fizz_buzz"] = "FizzBuzz" 
df.loc[(df.number%3==0) & (df.number%5!=0), "fizz_buzz"] = "Fizz" 
df.loc[(df.number%3!=0) & (df.number%5==0), "fizz_buzz"] = "Buzz" 


In [5]:
df

id  number fizz_buzz
0   0       1         1
1   1       2         2
2   2       3      Fizz
3   3       4         4
4   4       5      Buzz

In [6]:
def add_fizz_buzz_column(df):
    """ Return a dataframe with a new column added to `df` 
        titled "fizz_buzz" representing the Fizz Buzz value 
        for every number in the existing "number" column.
    """
    df['fizz_buzz'] = df['number']
    df.loc[(df.number%3==0) & (df.number%5==0), "fizz_buzz"] = "FizzBuzz" 
    df.loc[(df.number%3==0) & (df.number%5!=0), "fizz_buzz"] = "Fizz" 
    df.loc[(df.number%3!=0) & (df.number%5==0), "fizz_buzz"] = "Buzz" 
    
    return df

In [32]:

sample = [20, 2, 3, 4, 15, 6, 7, 8, 9, 10, 100, 800, 10000] 
dScore= pd.DataFrame({'sample':sample})


In [39]:
zscores = stats.zscore(sample)

In [8]:
dScore['Score'] = stats.zscore(dScore['sample'])
co=2
dScore = dScore.drop(dScore[(dScore.Score < -co) | (dScore.Score > co)].index)


In [9]:
dScore

sample     Score
0       20 -0.311159
1        2 -0.317949
2        3 -0.317571
3        4 -0.317194
4       15 -0.313045
5        6 -0.316440
6        7 -0.316063
7        8 -0.315685
8        9 -0.315308
9       10 -0.314931
10     100 -0.280983
11     800 -0.016945

In [10]:
mean_df = dScore['sample'].mean()
mean_df

82.0

Numpy 

Alternating columns

In [18]:
a = np.array([[0, 0, 1], [0, 0, 0], [1, 0, 1],[1, 1, 1]])
b = np.array([[0, 1, 2],[3, 4, 5]])

In [16]:
aD=[i for i in range(len(a[0])) if i%2==0]
aD

[0, 2]

In [22]:
cond= np.mod(a, 3)==0
cond

array([[ True,  True, False],
       [ True,  True,  True],
       [False,  True, False],
       [False, False, False]])

In [20]:
np.delete(b, [i for i in range(len(a[0])) if i%2!=0 and i!=0], axis=1)

array([[0, 2],
       [3, 5]])

Count Rows

In [29]:
a = np.array([[0, 0, 1],[0, 0, 0],[1, 0, 1],[1, 1, 1]])
a

array([[0, 0, 1],
       [0, 0, 0],
       [1, 0, 1],
       [1, 1, 1]])

In [30]:
np.count_nonzero(a == 1, axis=1)

array([1, 0, 2, 3], dtype=int64)